version: "3"
networks:
  snocode_default:
    external: true
services:
  userscriptjs:
    image: oven/bun
    # image: node
    # build: .
    working_dir: ${PWD}
    # command: bash -c "npm i -g bun && bun i && bun dev"
    # command: bash -c "bun i && bun --bun dev"
    # command: bash -c "bun i && bun --bun dev"
    command: bun --bun dev
    volumes:
      # - ./:${PWD}
      - ./..:${PWD}/..
    environment:
      - PORT=80
    restart: unless-stopped
    networks:
      - snocode_default
